### ISSUE TITLE
LowMem still getting OOM error with 3GB video card

### ISSUE THREAD

**Issue by 0reo** [deepfakes/faceswap#185]
funny thing is, this worked until I restarted my computer, without needed LowMem.  Now even with that on I can't get it to work.

```
python faceswap.py train -A ~/fake/test\ 1/dataset-hout/ -B ~/fake/test\ 1/dataset-bout/ -m ~/fake/test\ 1/model2 -p -t LowMem


Loading Trainer from Model_LowMem plugin...
Starting. Press "Enter" to stop training and save model
2018-02-11 19:59:53.337203: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-02-11 19:59:53.427226: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-02-11 19:59:53.427545: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 970M major: 5 minor: 2 memoryClockRate(GHz): 1.038
pciBusID: 0000:01:00.0
totalMemory: 2.94GiB freeMemory: 2.40GiB
2018-02-11 19:59:53.427562: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 970M, pci bus id: 0000:01:00.0, compute capability: 5.2)
2018-02-11 19:59:55.279372: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.21GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-02-11 19:59:55.394747: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.20GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-02-11 19:59:55.508315: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.29GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-02-11 19:59:55.618214: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.56GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-02-11 19:59:55.618267: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 544.75MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-02-11 19:59:55.618281: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 177.04MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-02-11 19:59:55.701532: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 547.38MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-02-11 19:59:55.727583: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 177.04MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-02-11 19:59:55.820789: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 520.38MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-02-11 19:59:55.825653: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 177.04MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-02-11 20:00:08.170371: W tensorflow/core/common_runtime/bfc_allocator.cc:273] Allocator (GPU_0_bfc) ran out of memory trying to allocate 72.00MiB.  Current allocation summary follows.
2018-02-11 20:00:08.170454: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (256): 	Total Chunks: 57, Chunks in use: 57. 14.2KiB allocated for chunks. 14.2KiB in use in bin. 564B client-requested in use in bin.
2018-02-11 20:00:08.170464: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (512): 	Total Chunks: 9, Chunks in use: 9. 4.5KiB allocated for chunks. 4.5KiB in use in bin. 4.5KiB client-requested in use in bin.
2018-02-11 20:00:08.170470: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (1024): 	Total Chunks: 18, Chunks in use: 18. 19.0KiB allocated for chunks. 19.0KiB in use in bin. 18.0KiB client-requested in use in bin.
2018-02-11 20:00:08.170476: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (2048): 	Total Chunks: 24, Chunks in use: 24. 48.2KiB allocated for chunks. 48.2KiB in use in bin. 48.0KiB client-requested in use in bin.
2018-02-11 20:00:08.170482: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (4096): 	Total Chunks: 10, Chunks in use: 10. 40.0KiB allocated for chunks. 40.0KiB in use in bin. 40.0KiB client-requested in use in bin.
2018-02-11 20:00:08.170488: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (8192): 	Total Chunks: 9, Chunks in use: 9. 72.0KiB allocated for chunks. 72.0KiB in use in bin. 72.0KiB client-requested in use in bin.
2018-02-11 20:00:08.170495: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (16384): 	Total Chunks: 10, Chunks in use: 10. 189.8KiB allocated for chunks. 189.8KiB in use in bin. 187.5KiB client-requested in use in bin.
2018-02-11 20:00:08.170501: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (32768): 	Total Chunks: 9, Chunks in use: 9. 337.5KiB allocated for chunks. 337.5KiB in use in bin. 337.5KiB client-requested in use in bin.
2018-02-11 20:00:08.170507: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (65536): 	Total Chunks: 9, Chunks in use: 9. 576.0KiB allocated for chunks. 576.0KiB in use in bin. 576.0KiB client-requested in use in bin.
2018-02-11 20:00:08.170514: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (131072): 	Total Chunks: 1, Chunks in use: 1. 128.0KiB allocated for chunks. 128.0KiB in use in bin. 128.0KiB client-requested in use in bin.
2018-02-11 20:00:08.170533: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (262144): 	Total Chunks: 1, Chunks in use: 0. 353.5KiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-02-11 20:00:08.170538: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (524288): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-02-11 20:00:08.170563: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (1048576): 	Total Chunks: 9, Chunks in use: 9. 10.97MiB allocated for chunks. 10.97MiB in use in bin. 10.12MiB client-requested in use in bin.
2018-02-11 20:00:08.170570: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (2097152): 	Total Chunks: 13, Chunks in use: 12. 39.22MiB allocated for chunks. 36.12MiB in use in bin. 35.25MiB client-requested in use in bin.
2018-02-11 20:00:08.170592: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (4194304): 	Total Chunks: 12, Chunks in use: 12. 53.38MiB allocated for chunks. 53.38MiB in use in bin. 53.00MiB client-requested in use in bin.
2018-02-11 20:00:08.170599: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (8388608): 	Total Chunks: 13, Chunks in use: 13. 150.03MiB allocated for chunks. 150.03MiB in use in bin. 144.50MiB client-requested in use in bin.
2018-02-11 20:00:08.170605: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (16777216): 	Total Chunks: 12, Chunks in use: 11. 217.32MiB allocated for chunks. 192.00MiB in use in bin. 192.00MiB client-requested in use in bin.
2018-02-11 20:00:08.170611: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (33554432): 	Total Chunks: 14, Chunks in use: 14. 450.03MiB allocated for chunks. 450.03MiB in use in bin. 420.00MiB client-requested in use in bin.
2018-02-11 20:00:08.170616: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (67108864): 	Total Chunks: 18, Chunks in use: 18. 1.20GiB allocated for chunks. 1.20GiB in use in bin. 1.20GiB client-requested in use in bin.
2018-02-11 20:00:08.170621: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (134217728): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-02-11 20:00:08.170626: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (268435456): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-02-11 20:00:08.170632: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin for 72.00MiB was 64.00MiB, Chunk State: 
2018-02-11 20:00:08.170638: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a80000 of size 1280
2018-02-11 20:00:08.170642: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a80500 of size 256
2018-02-11 20:00:08.170646: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a80600 of size 256
2018-02-11 20:00:08.170651: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a80700 of size 512
2018-02-11 20:00:08.170655: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a80900 of size 256
2018-02-11 20:00:08.170659: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a80a00 of size 256
2018-02-11 20:00:08.170663: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a80b00 of size 1024
2018-02-11 20:00:08.170667: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a80f00 of size 256
2018-02-11 20:00:08.170671: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a81000 of size 256
2018-02-11 20:00:08.170676: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a81100 of size 2048
2018-02-11 20:00:08.170680: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a81900 of size 256
2018-02-11 20:00:08.170684: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a81a00 of size 256
2018-02-11 20:00:08.170688: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a81b00 of size 256
2018-02-11 20:00:08.170692: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a81c00 of size 256
2018-02-11 20:00:08.170696: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a81d00 of size 65536
2018-02-11 20:00:08.170700: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a91d00 of size 256
2018-02-11 20:00:08.170704: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a91e00 of size 256
2018-02-11 20:00:08.170709: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a91f00 of size 8192
2018-02-11 20:00:08.170713: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a93f00 of size 256
2018-02-11 20:00:08.170717: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a94000 of size 256
2018-02-11 20:00:08.170721: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a94100 of size 4096
2018-02-11 20:00:08.170744: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a95100 of size 256
2018-02-11 20:00:08.170748: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a95200 of size 256
2018-02-11 20:00:08.170756: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a95300 of size 256
2018-02-11 20:00:08.170760: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a95400 of size 256
2018-02-11 20:00:08.170764: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a95500 of size 256
2018-02-11 20:00:08.170768: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a95600 of size 256
2018-02-11 20:00:08.170772: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a95700 of size 256
2018-02-11 20:00:08.170785: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a95800 of size 256
2018-02-11 20:00:08.170789: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a95900 of size 256
2018-02-11 20:00:08.170794: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a95a00 of size 256
2018-02-11 20:00:08.170798: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a95b00 of size 256
2018-02-11 20:00:08.170818: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a95c00 of size 38400
2018-02-11 20:00:08.170823: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04a9f200 of size 3276800
2018-02-11 20:00:08.170846: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe04dbf200 of size 13107200
2018-02-11 20:00:08.170850: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe05a3f200 of size 67108864
2018-02-11 20:00:08.170854: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe09a3f200 of size 33554432
2018-02-11 20:00:08.170858: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe0ba3f200 of size 75497472
2018-02-11 20:00:08.170863: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe1023f200 of size 18874368
2018-02-11 20:00:08.170867: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe1143f200 of size 4718592
2018-02-11 20:00:08.170871: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe118bf200 of size 1179648
2018-02-11 20:00:08.170875: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe119df200 of size 19200
2018-02-11 20:00:08.170879: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe119e3d00 of size 256
2018-02-11 20:00:08.170884: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe119e3e00 of size 256
2018-02-11 20:00:08.170887: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe119e3f00 of size 256
2018-02-11 20:00:08.170891: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe119e4000 of size 256
2018-02-11 20:00:08.170895: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe119e4100 of size 38400
2018-02-11 20:00:08.170899: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe119ed700 of size 3276800
2018-02-11 20:00:08.170904: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe11d0d700 of size 13107200
2018-02-11 20:00:08.170908: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe1298d700 of size 67108864
2018-02-11 20:00:08.170912: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe1698d700 of size 33554432
2018-02-11 20:00:08.170916: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe1898d700 of size 33554432
2018-02-11 20:00:08.170921: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe1a98d700 of size 75497472
2018-02-11 20:00:08.170925: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe1f18d700 of size 75497472
2018-02-11 20:00:08.170929: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe2398d700 of size 18874368
2018-02-11 20:00:08.170933: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe24b8d700 of size 18874368
2018-02-11 20:00:08.170937: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe25d8d700 of size 4718592
2018-02-11 20:00:08.170941: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe2620d700 of size 1179648
2018-02-11 20:00:08.170945: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe2632d700 of size 1179648
2018-02-11 20:00:08.170950: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe2644d700 of size 19200
2018-02-11 20:00:08.170954: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe26452200 of size 19200
2018-02-11 20:00:08.170958: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe26456d00 of size 38400
2018-02-11 20:00:08.170962: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe26460300 of size 4718592
2018-02-11 20:00:08.170966: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe268e0300 of size 3276800
2018-02-11 20:00:08.170970: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe26c00300 of size 19200
2018-02-11 20:00:08.170974: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe26c04e00 of size 19200
2018-02-11 20:00:08.170978: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe26c09900 of size 512
2018-02-11 20:00:08.170983: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe26c09b00 of size 512
2018-02-11 20:00:08.170987: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe26c09d00 of size 512
2018-02-11 20:00:08.170991: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe26c09f00 of size 1179648
2018-02-11 20:00:08.170995: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe26d29f00 of size 2097152
2018-02-11 20:00:08.170999: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe26f29f00 of size 1024
2018-02-11 20:00:08.171003: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe26f2a300 of size 1024
2018-02-11 20:00:08.171007: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe26f2a700 of size 1024
2018-02-11 20:00:08.171012: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe26f2ab00 of size 1024
2018-02-11 20:00:08.171016: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe26f2af00 of size 1024
2018-02-11 20:00:08.171020: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe26f2b300 of size 1024
2018-02-11 20:00:08.171024: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe26f2b700 of size 4718592
2018-02-11 20:00:08.171028: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe273ab700 of size 3276800
2018-02-11 20:00:08.171033: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe276cb700 of size 5111808
2018-02-11 20:00:08.171037: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe27bab700 of size 2048
2018-02-11 20:00:08.171041: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe27babf00 of size 2048
2018-02-11 20:00:08.171045: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe27bac700 of size 2048
2018-02-11 20:00:08.171049: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe27bacf00 of size 2048
2018-02-11 20:00:08.171053: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe27bad700 of size 2048
2018-02-11 20:00:08.171057: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe27badf00 of size 33554432
2018-02-11 20:00:08.171062: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe29badf00 of size 33554432
2018-02-11 20:00:08.171066: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe2bbadf00 of size 2048
2018-02-11 20:00:08.171070: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe2bbae700 of size 13107200
2018-02-11 20:00:08.171074: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe2c82e700 of size 33554432
2018-02-11 20:00:08.171078: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe2e82e700 of size 65536
2018-02-11 20:00:08.171082: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe2e83e700 of size 65536
2018-02-11 20:00:08.171087: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe2e84e700 of size 65536
2018-02-11 20:00:08.171091: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe2e85e700 of size 75497472
2018-02-11 20:00:08.171095: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe3305e700 of size 8192
2018-02-11 20:00:08.171099: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe33060700 of size 8192
2018-02-11 20:00:08.171103: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe33062700 of size 8192
2018-02-11 20:00:08.171107: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe33064700 of size 18874368
2018-02-11 20:00:08.171111: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe34264700 of size 18874368
2018-02-11 20:00:08.171116: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35464700 of size 4096
2018-02-11 20:00:08.171120: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35465700 of size 4096
2018-02-11 20:00:08.171124: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35466700 of size 4096
2018-02-11 20:00:08.171128: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35467700 of size 4718592
2018-02-11 20:00:08.171132: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe358e7700 of size 4718592
2018-02-11 20:00:08.171136: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35d67700 of size 2048
2018-02-11 20:00:08.171140: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35d67f00 of size 2048
2018-02-11 20:00:08.171144: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35d68700 of size 1179648
2018-02-11 20:00:08.171149: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35e88700 of size 65536
2018-02-11 20:00:08.171153: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35e98700 of size 256
2018-02-11 20:00:08.171157: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35e98800 of size 38400
2018-02-11 20:00:08.171161: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ea1e00 of size 512
2018-02-11 20:00:08.171166: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ea2000 of size 2048
2018-02-11 20:00:08.171170: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ea2800 of size 2048
2018-02-11 20:00:08.171174: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ea3000 of size 65536
2018-02-11 20:00:08.171178: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35eb3000 of size 8192
2018-02-11 20:00:08.171182: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35eb5000 of size 4096
2018-02-11 20:00:08.171187: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35eb6000 of size 2048
2018-02-11 20:00:08.171191: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35eb6800 of size 1024
2018-02-11 20:00:08.171195: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35eb6c00 of size 19200
2018-02-11 20:00:08.171199: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ebb700 of size 19200
2018-02-11 20:00:08.171203: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ec0200 of size 256
2018-02-11 20:00:08.171208: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ec0300 of size 38400
2018-02-11 20:00:08.171212: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ec9900 of size 512
2018-02-11 20:00:08.171216: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ec9b00 of size 1024
2018-02-11 20:00:08.171220: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ec9f00 of size 1024
2018-02-11 20:00:08.171225: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35eca300 of size 2048
2018-02-11 20:00:08.171229: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ecab00 of size 256
2018-02-11 20:00:08.171233: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ecac00 of size 2048
2018-02-11 20:00:08.171237: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ecb400 of size 65536
2018-02-11 20:00:08.171241: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35edb400 of size 38400
2018-02-11 20:00:08.171245: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ee4a00 of size 8192
2018-02-11 20:00:08.171249: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ee6a00 of size 512
2018-02-11 20:00:08.171254: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ee6c00 of size 4096
2018-02-11 20:00:08.171258: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ee7c00 of size 2048
2018-02-11 20:00:08.171262: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ee8400 of size 1024
2018-02-11 20:00:08.171266: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ee8800 of size 256
2018-02-11 20:00:08.171270: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ee8900 of size 256
2018-02-11 20:00:08.171275: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ee8a00 of size 256
2018-02-11 20:00:08.171279: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ee8b00 of size 256
2018-02-11 20:00:08.171283: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ee8c00 of size 256
2018-02-11 20:00:08.171287: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ee8d00 of size 256
2018-02-11 20:00:08.171291: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ee8e00 of size 256
2018-02-11 20:00:08.171295: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ee8f00 of size 256
2018-02-11 20:00:08.171299: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ee9000 of size 256
2018-02-11 20:00:08.171303: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ee9100 of size 38400
2018-02-11 20:00:08.171307: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ef2700 of size 256
2018-02-11 20:00:08.171312: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ef2800 of size 256
2018-02-11 20:00:08.171316: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ef2900 of size 512
2018-02-11 20:00:08.171320: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ef2b00 of size 1024
2018-02-11 20:00:08.171324: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ef2f00 of size 2048
2018-02-11 20:00:08.171328: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ef3700 of size 2048
2018-02-11 20:00:08.171332: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ef3f00 of size 256
2018-02-11 20:00:08.171351: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35ef4000 of size 65536
2018-02-11 20:00:08.171355: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35f04000 of size 256
2018-02-11 20:00:08.171373: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35f04100 of size 8192
2018-02-11 20:00:08.171377: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35f06100 of size 4096
2018-02-11 20:00:08.171381: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35f07100 of size 38400
2018-02-11 20:00:08.171386: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35f10700 of size 2048
2018-02-11 20:00:08.171390: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35f10f00 of size 256
2018-02-11 20:00:08.171394: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35f11000 of size 256
2018-02-11 20:00:08.171398: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35f11100 of size 512
2018-02-11 20:00:08.171402: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35f11300 of size 1024
2018-02-11 20:00:08.171406: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35f11700 of size 2048
2018-02-11 20:00:08.171410: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35f11f00 of size 2304
2018-02-11 20:00:08.171429: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35f12800 of size 1024
2018-02-11 20:00:08.171433: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35f12c00 of size 19200
2018-02-11 20:00:08.171452: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35f17700 of size 1792
2018-02-11 20:00:08.171456: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35f17e00 of size 65536
2018-02-11 20:00:08.171461: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35f27e00 of size 8192
2018-02-11 20:00:08.171465: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35f29e00 of size 4096
2018-02-11 20:00:08.171469: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35f2ae00 of size 2048
2018-02-11 20:00:08.171473: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35f2b600 of size 19200
2018-02-11 20:00:08.171478: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35f30100 of size 131072
2018-02-11 20:00:08.171482: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35fa8700 of size 1024
2018-02-11 20:00:08.171486: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35fa8b00 of size 256
2018-02-11 20:00:08.171490: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35fa8c00 of size 256
2018-02-11 20:00:08.171494: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35fa8d00 of size 256
2018-02-11 20:00:08.171499: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35fa8e00 of size 256
2018-02-11 20:00:08.171503: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35fa8f00 of size 256
2018-02-11 20:00:08.171507: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35fa9000 of size 256
2018-02-11 20:00:08.171511: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35fa9100 of size 2048
2018-02-11 20:00:08.171515: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35fa9900 of size 8192
2018-02-11 20:00:08.171519: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35fab900 of size 4096
2018-02-11 20:00:08.171523: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35fac900 of size 1024
2018-02-11 20:00:08.171528: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35facd00 of size 21504
2018-02-11 20:00:08.171532: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35fb2100 of size 256
2018-02-11 20:00:08.171536: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35fb2200 of size 256
2018-02-11 20:00:08.171540: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35fb2300 of size 256
2018-02-11 20:00:08.171544: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35fb2400 of size 256
2018-02-11 20:00:08.171548: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35fb2500 of size 2048
2018-02-11 20:00:08.171553: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35fb2d00 of size 4096
2018-02-11 20:00:08.171557: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe35fb3d00 of size 67108864
2018-02-11 20:00:08.171561: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe39fb3d00 of size 2048
2018-02-11 20:00:08.171566: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe39fb4500 of size 38400
2018-02-11 20:00:08.171570: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe39fbdb00 of size 3276800
2018-02-11 20:00:08.171574: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe3a2ddb00 of size 13107200
2018-02-11 20:00:08.171578: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe3af5db00 of size 67108864
2018-02-11 20:00:08.171597: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe3ef5db00 of size 75497472
2018-02-11 20:00:08.171601: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe4375db00 of size 75497472
2018-02-11 20:00:08.171606: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe47f5db00 of size 13107200
2018-02-11 20:00:08.171610: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe48bddb00 of size 67108864
2018-02-11 20:00:08.171614: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe4cbddb00 of size 33554432
2018-02-11 20:00:08.171618: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe4ebddb00 of size 75497472
2018-02-11 20:00:08.171623: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe533ddb00 of size 18874368
2018-02-11 20:00:08.171627: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe545ddb00 of size 1179648
2018-02-11 20:00:08.171631: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe546fdb00 of size 3276800
2018-02-11 20:00:08.171635: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe54a1db00 of size 13107200
2018-02-11 20:00:08.171639: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe5569db00 of size 67108864
2018-02-11 20:00:08.171644: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe5969db00 of size 33554432
2018-02-11 20:00:08.171648: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe5b69db00 of size 75497472
2018-02-11 20:00:08.171652: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe5fe9db00 of size 18874368
2018-02-11 20:00:08.171656: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe6109db00 of size 13107200
2018-02-11 20:00:08.171660: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe61d1db00 of size 4718592
2018-02-11 20:00:08.171665: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe6219db00 of size 3276800
2018-02-11 20:00:08.171669: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe624bdb00 of size 1179648
2018-02-11 20:00:08.171673: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe625ddb00 of size 3145728
2018-02-11 20:00:08.171678: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe628ddb00 of size 3145728
2018-02-11 20:00:08.171682: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe62bddb00 of size 3276800
2018-02-11 20:00:08.171686: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe62efdb00 of size 13107200
2018-02-11 20:00:08.171691: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe63b7db00 of size 67108864
2018-02-11 20:00:08.171695: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe67b7db00 of size 33554432
2018-02-11 20:00:08.171699: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe69b7db00 of size 33554432
2018-02-11 20:00:08.171703: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe6bb7db00 of size 75497472
2018-02-11 20:00:08.171706: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe7037db00 of size 1179648
2018-02-11 20:00:08.171711: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe7049db00 of size 2065152
2018-02-11 20:00:08.171727: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe70695e00 of size 18874368
2018-02-11 20:00:08.171734: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe71bae100 of size 4718592
2018-02-11 20:00:08.171739: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe7202e100 of size 33554432
2018-02-11 20:00:08.171758: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe7402e100 of size 3276800
2018-02-11 20:00:08.171762: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe7434e100 of size 33554432
2018-02-11 20:00:08.171766: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe7634e100 of size 13107200
2018-02-11 20:00:08.171771: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe76fce100 of size 16777216
2018-02-11 20:00:08.171779: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe77fce100 of size 35684352
2018-02-11 20:00:08.171784: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe7a1d6100 of size 67108864
2018-02-11 20:00:08.171788: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe7e1d6100 of size 16777216
2018-02-11 20:00:08.171792: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe7f1d6100 of size 4718592
2018-02-11 20:00:08.171796: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe7f656100 of size 14188544
2018-02-11 20:00:08.171800: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe803de100 of size 33554432
2018-02-11 20:00:08.171804: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe823de100 of size 75497472
2018-02-11 20:00:08.171809: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe86bde100 of size 16777216
2018-02-11 20:00:08.171813: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe87bde100 of size 8388608
2018-02-11 20:00:08.171817: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe883de100 of size 8388608
2018-02-11 20:00:08.171836: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe88bde100 of size 4194304
2018-02-11 20:00:08.171841: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe88fde100 of size 8388608
2018-02-11 20:00:08.171845: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0xe897de100 of size 4194304
2018-02-11 20:00:08.171850: I tensorflow/core/common_runtime/bfc_allocator.cc:670] Free at 0xe35f50100 of size 361984
2018-02-11 20:00:08.171855: I tensorflow/core/common_runtime/bfc_allocator.cc:670] Free at 0xe71895e00 of size 3244800
2018-02-11 20:00:08.171859: I tensorflow/core/common_runtime/bfc_allocator.cc:670] Free at 0xe89bde100 of size 26550016
2018-02-11 20:00:08.171863: I tensorflow/core/common_runtime/bfc_allocator.cc:676]      Summary of in-use Chunks by size: 
2018-02-11 20:00:08.171870: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 57 Chunks of size 256 totalling 14.2KiB
2018-02-11 20:00:08.171875: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 9 Chunks of size 512 totalling 4.5KiB
2018-02-11 20:00:08.171879: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 16 Chunks of size 1024 totalling 16.0KiB
2018-02-11 20:00:08.171884: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 1 Chunks of size 1280 totalling 1.2KiB
2018-02-11 20:00:08.171889: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 1 Chunks of size 1792 totalling 1.8KiB
2018-02-11 20:00:08.171893: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 23 Chunks of size 2048 totalling 46.0KiB
2018-02-11 20:00:08.171898: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 1 Chunks of size 2304 totalling 2.2KiB
2018-02-11 20:00:08.171903: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 10 Chunks of size 4096 totalling 40.0KiB
2018-02-11 20:00:08.171921: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 9 Chunks of size 8192 totalling 72.0KiB
2018-02-11 20:00:08.171926: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 9 Chunks of size 19200 totalling 168.8KiB
2018-02-11 20:00:08.171945: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 1 Chunks of size 21504 totalling 21.0KiB
2018-02-11 20:00:08.171950: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 9 Chunks of size 38400 totalling 337.5KiB
2018-02-11 20:00:08.171955: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 9 Chunks of size 65536 totalling 576.0KiB
2018-02-11 20:00:08.171960: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 1 Chunks of size 131072 totalling 128.0KiB
2018-02-11 20:00:08.171964: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 8 Chunks of size 1179648 totalling 9.00MiB
2018-02-11 20:00:08.171969: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 1 Chunks of size 2065152 totalling 1.97MiB
2018-02-11 20:00:08.171974: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 1 Chunks of size 2097152 totalling 2.00MiB
2018-02-11 20:00:08.171992: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 2 Chunks of size 3145728 totalling 6.00MiB
2018-02-11 20:00:08.171997: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 9 Chunks of size 3276800 totalling 28.12MiB
2018-02-11 20:00:08.172002: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 2 Chunks of size 4194304 totalling 8.00MiB
2018-02-11 20:00:08.172006: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 9 Chunks of size 4718592 totalling 40.50MiB
2018-02-11 20:00:08.172011: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 1 Chunks of size 5111808 totalling 4.88MiB
2018-02-11 20:00:08.172016: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 3 Chunks of size 8388608 totalling 24.00MiB
2018-02-11 20:00:08.172020: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 9 Chunks of size 13107200 totalling 112.50MiB
2018-02-11 20:00:08.172025: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 1 Chunks of size 14188544 totalling 13.53MiB
2018-02-11 20:00:08.172030: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 3 Chunks of size 16777216 totalling 48.00MiB
2018-02-11 20:00:08.172034: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 8 Chunks of size 18874368 totalling 144.00MiB
2018-02-11 20:00:08.172039: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 13 Chunks of size 33554432 totalling 416.00MiB
2018-02-11 20:00:08.172044: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 1 Chunks of size 35684352 totalling 34.03MiB
2018-02-11 20:00:08.172048: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 8 Chunks of size 67108864 totalling 512.00MiB
2018-02-11 20:00:08.172053: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 10 Chunks of size 75497472 totalling 720.00MiB
2018-02-11 20:00:08.172058: I tensorflow/core/common_runtime/bfc_allocator.cc:683] Sum Total of in-use chunks: 2.08GiB
2018-02-11 20:00:08.172064: I tensorflow/core/common_runtime/bfc_allocator.cc:685] Stats: 
Limit:                  2259353600
InUse:                  2229196800
MaxInUse:               2255313920
NumAllocs:                     650
MaxAllocSize:            591602944

2018-02-11 20:00:08.172081: W tensorflow/core/common_runtime/bfc_allocator.cc:277] ***************************************************************************************************_
2018-02-11 20:00:08.172094: W tensorflow/core/framework/op_kernel.cc:1192] Resource exhausted: OOM when allocating tensor with shape[2048,1024,3,3]
OOM when allocating tensor with shape[2048,1024,3,3]
	 [[Node: model_1/conv2d_4/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model_1/reshape_1/Reshape, conv2d_4/kernel/read)]]
	 [[Node: loss_1/mul/_331 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1469_loss_1/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'model_1/conv2d_4/convolution', defined at:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/storage/.home_folders/Development/faceswap/scripts/train.py", line 125, in processThread
    model = PluginLoader.get_model(trainer)(get_folder(self.arguments.model_dir))
  File "/storage/.home_folders/Development/faceswap/lib/ModelAE.py", line 19, in __init__
    self.initModel()
  File "/storage/.home_folders/Development/faceswap/plugins/Model_LowMem.py", line 20, in initModel
    self.autoencoder_A = KerasModel(x, self.decoder_A(self.encoder(x)))
  File "/storage/.home_folders/Development/faceswap/faceswap_env/lib/python3.6/site-packages/keras/engine/topology.py", line 603, in __call__
    output = self.call(inputs, **kwargs)
  File "/storage/.home_folders/Development/faceswap/faceswap_env/lib/python3.6/site-packages/keras/engine/topology.py", line 2061, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "/storage/.home_folders/Development/faceswap/faceswap_env/lib/python3.6/site-packages/keras/engine/topology.py", line 2212, in run_internal_graph
    output_tensors = _to_list(layer.call(computed_tensor, **kwargs))
  File "/storage/.home_folders/Development/faceswap/faceswap_env/lib/python3.6/site-packages/keras/layers/convolutional.py", line 164, in call
    dilation_rate=self.dilation_rate)
  File "/storage/.home_folders/Development/faceswap/faceswap_env/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 3195, in conv2d
    data_format=tf_data_format)
  File "/storage/.home_folders/Development/faceswap/faceswap_env/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 751, in convolution
    return op(input, filter)
  File "/storage/.home_folders/Development/faceswap/faceswap_env/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 835, in __call__
    return self.conv_op(inp, filter)
  File "/storage/.home_folders/Development/faceswap/faceswap_env/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 499, in __call__
    return self.call(inp, filter)
  File "/storage/.home_folders/Development/faceswap/faceswap_env/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 187, in __call__
    name=self.name)
  File "/storage/.home_folders/Development/faceswap/faceswap_env/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 631, in conv2d
    data_format=data_format, name=name)
  File "/storage/.home_folders/Development/faceswap/faceswap_env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/storage/.home_folders/Development/faceswap/faceswap_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/storage/.home_folders/Development/faceswap/faceswap_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[2048,1024,3,3]
	 [[Node: model_1/conv2d_4/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model_1/reshape_1/Reshape, conv2d_4/kernel/read)]]
	 [[Node: loss_1/mul/_331 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1469_loss_1/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

```

## Steps to reproduce

tried different training types, tried deleting old training data, tried reinstalling faceswap

## Other relevant information

- **Operating system and version:** ubuntu 17.10
- **Python version:** 3.6.3
- **Faceswap version:** 20753a64b76a156aea17724348269d60dd525f87
- **Faceswap method:** GPU
- ...

**Comment by Deadfishzzway** [comment]
Have you tried the lower batch size option, like -bs 32. It worked for me.
Also I would like to know what VRAM size is required to run the original trainer and does training data change the required VRAM size?

**Comment by fetchlister** [comment]
For what its worth the original trainer worked at the default batch size of 64 on my 4 GB m2200m

**Comment by k3erg** [comment]
You can further reduce the VRAM needed by using `- t LowMem -s 16` and editing Model_LowMem.py as follows:

`13: ENCODER_DIM = 256`
and

`51: #x = self.conv(512)(x)`

Obviously, this comes at a price, but training even on my old MacBook Pro with Nvidia 750m*  is 60x as fast as on my new maxed-out MacBook Pro with no GPU support.

*yes you can compile tensorflow 1.4 with GPU support for macOS, pm if instructions needed.

**Comment by Clorr** [comment]
Please reopen in faceswap-playground if still relevant. Thanks
