### ISSUE TITLE
Crash upon training

### ISSUE THREAD

**Issue by jasonTong68** [deepfakes/faceswap#772]
Upon training a model, a crash occurs, and then the process exits.

Here's the crash report:
https://pastebin.com/hzkpzNib

And here's the log:

```
06/24/2019 23:15:17 INFO     Loading data, this may take a while...
06/24/2019 23:15:17 INFO     Loading Model from Original plugin...
06/24/2019 23:15:23 WARNING  No existing state file found. Generating.
06/24/2019 23:15:23 WARNING  From C:\Users\James\Anaconda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nColocations handled automatically by placer.
06/24/2019 23:15:25 INFO     Creating new 'original' model in folder: 'F:\faceswap\Models\lzl_choi_model'
06/24/2019 23:15:25 INFO     Loading Trainer from Original plugin...
06/24/2019 23:15:28 INFO     Enabled TensorBoard Logging
06/24/2019 23:15:29 WARNING  From C:\Users\James\Anaconda3\envs\faceswap\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nUse tf.cast instead.
06/24/2019 23:15:53 CRITICAL Error caught! Exiting...
06/24/2019 23:15:53 ERROR    Caught exception in thread: 'training_0'
06/24/2019 23:15:58 ERROR    Got Exception on main handler:
Traceback (most recent call last):
File "C:\Users\James\faceswap\lib\cli.py", line 119, in execute_script
process.process()
File "C:\Users\James\faceswap\scripts\train.py", line 98, in process
self.end_thread(thread, err)
File "C:\Users\James\faceswap\scripts\train.py", line 123, in end_thread
thread.join()
File "C:\Users\James\faceswap\lib\multithreading.py", line 460, in join
raise thread.err[1].with_traceback(thread.err[2])
File "C:\Users\James\faceswap\lib\multithreading.py", line 390, in run
self._target(*self._args, **self._kwargs)
File "C:\Users\James\faceswap\scripts\train.py", line 149, in training
raise err
File "C:\Users\James\faceswap\scripts\train.py", line 139, in training
self.run_training_cycle(model, trainer)
File "C:\Users\James\faceswap\scripts\train.py", line 220, in run_training_cycle
trainer.train_one_step(viewer, timelapse)
File "C:\Users\James\faceswap\plugins\train\trainer\_base.py", line 165, in train_one_step
loss[side] = batcher.train_one_batch(do_preview)
File "C:\Users\James\faceswap\plugins\train\trainer\_base.py", line 249, in train_one_batch
loss = self.model.predictors[self.side].train_on_batch(*batch)
File "C:\Users\James\Anaconda3\envs\faceswap\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
outputs = self.train_function(ins)
File "C:\Users\James\Anaconda3\envs\faceswap\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
return self._call(inputs)
File "C:\Users\James\Anaconda3\envs\faceswap\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
fetched = self._callable_fn(*array_vals)
File "C:\Users\James\Anaconda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
run_metadata_ptr)
File "C:\Users\James\Anaconda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[64,32,32,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
[[{{node decoder_b/conv2d_7/BiasAdd-1-1-TransposeNCHWToNHWC-LayoutOptimizer}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

[[{{node training_1/Adam/gradients/AddN_1}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

06/24/2019 23:15:58 CRITICAL An unexpected crash has occurred. Crash report written to C:\Users\James\Desktop\crash_report.2019.06.24.231553824799.log. Please verify you are running the latest version of faceswap before reporting
Exception ignored in: <generator object TrainingDataGenerator.minibatch at 0x00000215F7C396D0>
Traceback (most recent call last):
File "C:\Users\James\faceswap\lib\training_data.py", line 148, in minibatch
File "C:\Users\James\faceswap\lib\multithreading.py", line 48, in __exit__
File "C:\Users\James\faceswap\lib\multithreading.py", line 40, in free
File "C:\Users\James\faceswap\lib\multithreading.py", line 178, in free
File "<string>", line 2, in put
File "C:\Users\James\Anaconda3\envs\faceswap\lib\multiprocessing\managers.py", line 753, in _callmethod
File "C:\Users\James\Anaconda3\envs\faceswap\lib\multiprocessing\managers.py", line 740, in _connect
File "C:\Users\James\Anaconda3\envs\faceswap\lib\multiprocessing\connection.py", line 485, in Client
File "C:\Users\James\Anaconda3\envs\faceswap\lib\multiprocessing\connection.py", line 686, in PipeClient
FileNotFoundError: [WinError 2] The system cannot find the file specified
Exception ignored in: <generator object TrainingDataGenerator.minibatch at 0x00000215F7C394C0>
Traceback (most recent call last):
File "C:\Users\James\faceswap\lib\training_data.py", line 148, in minibatch
File "C:\Users\James\faceswap\lib\multithreading.py", line 48, in __exit__
File "C:\Users\James\faceswap\lib\multithreading.py", line 40, in free
File "C:\Users\James\faceswap\lib\multithreading.py", line 178, in free
File "<string>", line 2, in put
File "C:\Users\James\Anaconda3\envs\faceswap\lib\multiprocessing\managers.py", line 753, in _callmethod
File "C:\Users\James\Anaconda3\envs\faceswap\lib\multiprocessing\managers.py", line 740, in _connect
File "C:\Users\James\Anaconda3\envs\faceswap\lib\multiprocessing\connection.py", line 485, in Client
File "C:\Users\James\Anaconda3\envs\faceswap\lib\multiprocessing\connection.py", line 686, in PipeClient
FileNotFoundError: [WinError 2] The system cannot find the file specified
Process exited.
```

**Comment by torzdf** [comment]
https://github.com/deepfakes/faceswap-playground/issues/283

**Comment by jasonTong68** [comment]
> [deepfakes/faceswap-playground#283](https://github.com/deepfakes/faceswap-playground/issues/283)

I don't think this is a duplicate of that issue. Changing the batch size does not affect the result either.

The error given is "FileNotFoundError: [WinError 2] The system cannot find the file specified", not "ResourceExhaustedError" in the issue you mentioned.

**Comment by torzdf** [comment]
It is the same issue. You are out of memory.

**Comment by jasonTong68** [comment]
I've turned down the batch size to 2, enabled Ping Pong and Memory Saving Gradients, but it still crashes. However, ResourceExhaustedError does not appear in the crash report now.

Crash report: https://pastebin.com/iSysUfKH

**Comment by gessyoo** [comment]
@jasonTong68, reboot and close all other programs that might be using GPU memory.  Try training with the Lightweight model instead of the IAE model.

**Comment by jasonTong68** [comment]
Seems to be working now, many thanks
